# Downloading 30-Year Climate Normals and Departures From Normal

In this example, we will download the daily, monthly and yearly normals for Denver, CO (KDEN)

Here is the documentation for the functions that download historical ACIS2 Data:

1) [Get Single Station Data](https://github.com/edrewitz/xmACIS2Py/blob/main/Documentation/xmACIS2.0/data_access.md#get_single_station_acis_data)
2) [Get Multi Station Data](https://github.com/edrewitz/xmACIS2Py/blob/main/Documentation/xmACIS2.0/data_access.md#get_multi_station_acis_data)
3) [Get Single Station Climate Normals](https://github.com/edrewitz/xmACIS2Py/blob/main/Documentation/xmACIS2.0/data_access.md#get_single_station_climate_normals)
4) [Get Multi Station Climate Normals](https://github.com/edrewitz/xmACIS2Py/blob/main/Documentation/xmACIS2.0/data_access.md#get_multi_station_climate_normals)
5) [Get Single Station Departures From Normal](https://github.com/edrewitz/xmACIS2Py/blob/main/Documentation/xmACIS2.0/data_access.md#get_single_station_departures)
6) [Get Multi Station Departures From Normal](https://github.com/edrewitz/xmACIS2Py/blob/main/Documentation/xmACIS2.0/data_access.md#get_multi_station_departures)

## Imports

In [1]:
import xmacis2py as xmacis

## Download Daily Monthly and Yearly Normals

In [2]:
daily_normals = xmacis.get_single_station_climate_normals('kden', 
                                                          start_date='2025-01-01', 
                                                          end_date='2025-12-31')

In [3]:
daily_normals

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Heating Degree Days,Cooling Degree Days,Growing Degree Days,Precipitation,Snowfall
0,2025-01-01,44,18,31.0,34,0,0,0.01,NaN
1,2025-01-02,44,18,31.1,34,0,0,0.02,NaN
2,2025-01-03,44,18,31.2,34,0,0,0.01,NaN
3,2025-01-04,44,18,31.3,34,0,0,0.01,NaN
4,2025-01-05,44,18,31.4,34,0,0,0.01,NaN
...,...,...,...,...,...,...,...,...,...
360,2025-12-27,44,18,30.6,34,0,0,0.01,NaN
361,2025-12-28,44,18,30.7,34,0,0,0.01,NaN
362,2025-12-29,44,18,30.8,34,0,0,0.02,NaN
363,2025-12-30,44,18,30.9,34,0,0,0.01,NaN
364,2025-12-31,44,18,30.9,34,0,0,0.01,NaN

In [4]:
monthly_normals = xmacis.get_single_station_climate_normals('kden', 
                                                            start_date='2025-01-01', 
                                                            end_date='2025-12-31',
                                                            interval='monthly')

In [5]:
monthly_normals

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Heating Degree Days,Cooling Degree Days,Growing Degree Days,Precipitation,Snowfall
0,2025-01-01,45,19,31.7,1034,0,2,0.38,NaN
1,2025-02-01,46,20,32.7,904,0,4,0.41,NaN
2,2025-03-01,56,28,41.6,726,0,32,0.86,NaN
3,2025-04-01,62,34,47.8,517,1,79,1.68,NaN
4,2025-05-01,71,44,57.4,261,26,264,2.16,NaN
5,2025-06-01,83,53,68.2,52,147,547,1.94,NaN
6,2025-07-01,90,60,75.1,4,315,776,2.14,NaN
7,2025-08-01,88,58,72.9,9,254,710,1.58,NaN
8,2025-09-01,80,50,64.8,105,99,453,1.35,NaN
9,2025-10-01,65,37,51.1,436,7,147,0.99,NaN
10,2025-11-01,53,26,39.4,767,0,26,0.64,NaN
11,2025-12-01,44,18,31.2,1048,0,3,0.35,NaN

In [6]:
annual_normals = xmacis.get_single_station_climate_normals('kden', 
                                                            start_date='2025-01-01', 
                                                            end_date='2025-12-31',
                                                            interval='yearly')

In [7]:
annual_normals

,Date,Maximum Temperature,Minimum Temperature,Average Temperature,Heating Degree Days,Cooling Degree Days,Growing Degree Days,Precipitation,Snowfall
0,2025-01-01,65,37,51.2,5862,850,3044,14.48,NaN

## Download Daily Monthly and Yearly Departures From Normal

In [8]:
daily_departures = xmacis.get_single_station_departures('kden', 
                                                        start_date='2025-01-01', 
                                                        end_date='2025-12-31')

In [9]:
daily_departures

,Date,Maximum Temperature Departure,Minimum Temperature Departure,Average Temperature Departure,Heating Degree Days Departure,Cooling Degree Days Departure,Growing Degree Days Departure,Precipitation Departure,Snowfall Departure
0,2025-01-01,-3,-7,-5.0,5,0,0,-0.01,NaN
1,2025-01-02,6,0,2.9,-3,0,0,-0.02,NaN
2,2025-01-03,6,0,2.8,-3,0,0,-0.01,NaN
3,2025-01-04,-20,-3,-11.8,11,0,0,0.01,NaN
4,2025-01-05,-17,-7,-12.4,12,0,0,-0.01,NaN
...,...,...,...,...,...,...,...,...,...
360,2025-12-27,16,16,16.4,-16,0,0,-0.01,NaN
361,2025-12-28,-6,-9,-7.7,8,0,0,0.06,NaN
362,2025-12-29,-5,-10,-7.3,7,0,0,-0.02,NaN
363,2025-12-30,7,-1,3.1,-3,0,0,-0.01,NaN
364,2025-12-31,21,6,13.6,-14,0,0,-0.01,NaN

In [10]:
monthly_departures = xmacis.get_single_station_departures('kden', 
                                                        start_date='2025-01-01', 
                                                        end_date='2025-12-31',
                                                        interval='monthly')

In [11]:
monthly_departures

,Date,Maximum Temperature Departure,Minimum Temperature Departure,Average Temperature Departure,Heating Degree Days Departure,Cooling Degree Days Departure,Growing Degree Days Departure,Precipitation Departure,Snowfall Departure
0,2025-01-01,-6,-6,-5.9,174,0,-2,0.14,NaN
1,2025-02-01,0,-3,-1.5,36,0,2,-0.19,NaN
2,2025-03-01,6,3,4.2,-139,0,16,0.40,NaN
3,2025-04-01,3,1,1.7,-53,3,37,-1.18,NaN
4,2025-05-01,0,0,0.3,-29,-13,-10,1.41,NaN
5,2025-06-01,0,2,0.8,-16,14,29,0.29,NaN
6,2025-07-01,1,-1,0.0,-4,5,9,-1.50,NaN
7,2025-08-01,0,1,0.9,-9,25,34,2.54,NaN
8,2025-09-01,-2,1,-0.1,-44,-38,-3,0.41,NaN
9,2025-10-01,3,2,2.4,-76,3,31,-0.85,NaN
10,2025-11-01,7,4,5.7,-178,0,30,-0.55,NaN
11,2025-12-01,13,9,11.1,-353,0,32,-0.02,NaN

In [12]:
annual_departures = xmacis.get_single_station_departures('kden', 
                                                        start_date='2025-01-01', 
                                                        end_date='2025-12-31',
                                                        interval='yearly')

In [13]:
annual_departures

,Date,Maximum Temperature Departure,Minimum Temperature Departure,Average Temperature Departure,Heating Degree Days Departure,Cooling Degree Days Departure,Growing Degree Days Departure,Precipitation Departure,Snowfall Departure
0,2025-01-01,2,1,1.7,-691,-2,207,0.9,NaN